# 1)Wrirte a program to create a 5 dimensional array with all zeros and ones

In [32]:
import numpy as np

In [33]:
x = np.zeros([1,2,3,4,5])

In [34]:
x.ndim

5

In [35]:
x

array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]]])

In [36]:
x = np.ones([1,2,3,4,6])

In [37]:
x.ndim

5

In [38]:
x

array([[[[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]]]]])

   # 2)Write a program to create an array of 10zeros,10ones,and 10fives in row 1 2 and 3 which create a new array of shape(3,10)

In [39]:
zeros = np.zeros(10)
ones = np.ones(10)
fives = np.full(10,5)
new_array = np.array([zeros,ones,fives])

In [40]:
print(new_array)
print("shape:",new_array.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
shape: (3, 10)


# 3)Write a program to create a 3x4 matrix filled with values from 10 to 21

In [9]:
y = np.arange(10,22).reshape(3,4)

In [10]:
y

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# 4)Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,

In [41]:
h = np.diag([0,1,2,3,4,5,6,7,8,9])

In [42]:
h

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

# 5)Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns

In [16]:
a  = np.arange(1,17).reshape(4,4)

In [17]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
a[: : 1,: : -1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

# 6)Write a program to reverse an array (the first element becomes the last).

Given array:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]

In [43]:
f = np.arange(11,28)

In [44]:
f

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [45]:
f[: : -1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

# 7)Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100

In [57]:
h = np.arange(1,101).reshape(10,10)

In [58]:
h

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [59]:
h[(h>=30) & (h<=80)]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [61]:
c=h[((h>=30) & (h<=80)) & (h%5==0)]

In [62]:
c

array([30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80])

# 8)Write a program to create a 2D array with 1 on the border and 0 inside.

In [63]:
arr = np.ones((5,5))

In [64]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
arr.ndim

2

In [66]:
arr[1:-1,1:-1] = 0

In [67]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# 9)Write a program to create a checkerboard pattern .Don't use default array function

Checkerboard pattern:                                                  

[[0 1 0 1 0 1 0 1]                                                      

 [1 0 1 0 1 0 1 0]                                                      

 [0 1 0 1 0 1 0 1]                                                      

 [1 0 1 0 1 0 1 0]                                                      

 [0 1 0 1 0 1 0 1]                                                      

 [1 0 1 0 1 0 1 0]                                                      

 [0 1 0 1 0 1 0 1]                                                      

 [1 0 1 0 1 0 1 0]]

In [83]:
ae = np.ones((3,3))
ae = np.zeros((8,8),dtype=int)
ae[1::2,::2]=1
ae[::2,1::2]=1

In [84]:
ae

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 10)Write a program to find common values between two arrays.

Expected Output:

array1: [10 20 40 60]

array2: [10, 30, 40,50]

In [68]:
array1 = [10,20,40,60]
array2 = [10,30,40,50]

In [70]:
array1

[10, 20, 40, 60]

In [71]:
array2

[10, 30, 40, 50]

In [72]:
np.intersect1d(array1,array2)

array([10, 40])

# 11)Write a program to create an array 2d array and then reshape into 1d array

In [73]:
s = np.array([[2,4,6],[7,1,3]])

In [74]:
s

array([[2, 4, 6],
       [7, 1, 3]])

In [75]:
w = s.ravel()

In [76]:
w.ndim

1

# 12)Write a user defined function for creating a 1 or 2d array from scratch without using array functions

In [80]:
N = 5
ar = [1]*N
print(ar)

[1, 1, 1, 1, 1]
